###█▀▀ █▀▀ █░░ █░░ █▀▀█ █░░ █░░
##▀▀█ █▀▀ █░░ █░░ █▄▄█ █░░ █░░
#▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀ ▀▀▀
#DO NOT CHANGE
cfgversion: 1.3

#groups of items to sell in your inventory when you do /sell GROUPNAME
#you can have an infinite longer of groups, as long as they all have a success, failed and items variable.
#if you don't want to use this feature just remove all groups
groups:
  ores:
    success: "&a&lSuccess! &r&7sold all your ores for §8${MONEY}"
    failed: "&c&lError: &r&7you don't have any ores to sell"
    items:
      - 14
      - 15
      - 16
      - 21
      - 56
      - 73
      - 129
      - 266
      - 265
      - 263
      - 351
      - 264
      - 331
      - 388
  test:
    success: "&a&lSuccess! &r&7sold test group items for §8${MONEY}"
    failed: "&c&lError: &r&7you don't have any items to sell"
    items:
    - 4
    - 1
    - 3

# CONFIG: Selling prices & sellable items
#put all the ids and their price in here. (feel free to change everything)
#prices based off https://pastebin.com/uH7waTt9

1: 1
4: 1
14: 4
15: 3
16: 2
17: 4
21: 2
22: 18
41: 36
42: 27
56: 5
57: 45
73: 1
74: 9
83: 1
81: 2
86: 3
103: 9
129: 6
133: 54
152: 9
173: 9
331: 1
263: 2
264: 5
265: 3
266: 4
331: 1
360: 1
388: 1
406: 1
391: 2
392: 2
296: 2
295: 1
338: 2
434: 2